GET http://127.0.0.1:8000/

###
POST http://127.0.0.1:8000/articles
Content-Type: application/json

{
  "article": {
    "title": "Article 1",
    "description": "Description 1",
    "body": "Content 1"
  }
}

###
GET http://127.0.0.1:8000/articles/2
Content-Type: application/json

###
GET http://127.0.0.1:8000/article/

###
POST http://127.0.0.1:8000/article/
Content-Type: application/json

{
  "article": {
    "title": "Article 6",
    "description": "Description 6",
    "body": "Content 6"
  }
}

